// DOCKER_SAMPLE/web/src/components/auth/LogIn.svelte
<script lang="ts">
    import { userStore } from 'src/stores';
    import { tick } from 'svelte';

    let loginInfo = {
        email: '',
        password: '',
    };
    let errorMessage = '';
    const handleLogin = async (e: SubmitEvent) => {
        e.preventDefault();
        $userStore.fetching = true;

        if (!loginInfo.email || !loginInfo.password) {
            $userStore.fetching = false;
            errorMessage = 'Please fill out all fields';
            setTimeout(() => {
                errorMessage = '';
            }, 3000);
        }
        const res = await fetch('/api/account/login', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(loginInfo),
        });
        const data = await res.json();
        if (data.message) {
            errorMessage = data.message;
            userStore.set({
                fetching: false,
                user: undefined,
            });
            setTimeout(() => {
                errorMessage = '';
            }, 3000);
        } else if (data.token) {
            localStorage.setItem('token', data.token);
            userStore.set({
                fetching: false,
                user: data.account,
            });
        }
    };
</script>

<form action="POST" name="login" class="login" on:submit={handleLogin}>
    <h2>Log In</h2>
    <div class="group">
        <input
            type="email"
            placeholder="Email"
            name="email"
            required
            bind:value={loginInfo.email}
        />
        <input
            type="password"
            placeholder="Password"
            name="password"
            required
            bind:value={loginInfo.password}
        />
    </div>
    {#if errorMessage}
        <div class="error">{errorMessage}</div>
    {/if}
    <button type="submit">Login</button>
</form>

<style lang="scss">
    .login {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 0.8em;
        padding: 4em;
        padding-top: 1em;
        .group {
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 0.4em;
        }
        & > * {
            width: 100%;
        }
        .error {
            color: var(--color-warning-dark);
        }
    }
</style>

// src/pages/Login/index.jsx
import { useForm } from "react-hook-form";
import { useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import { loginSchema } from "../../common/utils";
import Header from "../../components/Header";
import { useYupValidationResolver } from "../../hooks/useYupValidationResolver";
import { addDetails } from "../../redux/sharedSlices/user";
// styles
import "./styles.scss";

const Login = () => {
  const validationResolver = useYupValidationResolver(loginSchema);
  const dispatch = useDispatch()

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    mode: "onBlur",
    resolver: validationResolver,
  });

  const navigate = useNavigate();

  const onSubmit = async (data) => {
    const response = await fetch("http://localhost/api/account/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        ...data,
      }),
    });
    const responseData = await response.json();

    if (responseData.message) {
      toast(responseData.message, {
        type: "error",
      });
    } else {
      dispatch(addDetails(responseData))
      toast("Sign up successfull", {
        type: "success",
      });
      navigate("/");
    }
    // if (data.message) {
    //     errorMessage = data.message;
    // }
    // if (data.token) {
    //     localStorage.setItem('token', data.token);
    // }
  };
  return (
    <>
      <Header />
      <div className="login">
        <h2>Login</h2>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="form-group">
            <label>Email</label>
            <input
              type="email"
              placeholder="Enter Your Email"
              name="email"
              {...register("email", { required: true })}
            />
            {errors?.email && (
              <span className="error-mesage">{errors?.email.message}</span>
            )}
          </div>
          <div className="form-group">
            <label>Password</label>
            <input
              type="Password"
              placeholder="Password"
              {...register("password", { required: true })}
            />
            {errors?.password && (
              <span className="error-mesage">{errors?.password.message}</span>
            )}
          </div>
          <div className="form-group">
            <button className="submin_btn" type="submit">
              Login
            </button>
          </div>
        </form>
        <span onClick={()=>navigate("/signup")} className="sign_up">Sign up</span>
      </div>
    </>
  );
};

export default Login;
