// src/pages/Signup/index.jsx
import Header from "../../components/Header";
import Select from "react-select";
import makeAnimated from "react-select/animated";
// styles
import { useForm, Controller } from "react-hook-form";
import "./style.scss";
import { errorMessages, schema } from "../../common/utils";
import { useCallback, useState } from "react";
import { toast } from "react-toastify";
import { cities, counties, countries, states } from "./data";
import { useNavigate } from "react-router-dom";

export const useYupValidationResolver = (validationSchema) =>
  useCallback(
    async (data) => {
      try {
        const values = await validationSchema.validate(data, {
          abortEarly: false,
        });

        return {
          values,
          errors: {},
        };
      } catch (errors) {
        return {
          values: {},
          errors: errors.inner.reduce(
            (allErrors, currentError) => ({
              ...allErrors,
              [currentError.path]: {
                type: currentError.type ?? "validation",
                message: currentError.message,
              },
            }),
            {}
          ),
        };
      }
    },
    [validationSchema]
  );

const Signup = () => {
  const [pfp, setPfp] = useState({
    file: "",
    extension: "",
  });

  const [profilePicErr, setProfilePicErr] = useState("");

  const animatedComponents = makeAnimated();

  const validationResolver = useYupValidationResolver(schema);
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
  } = useForm({
    mode: "onBlur",
    resolver: validationResolver,
  });

  const navigate = useNavigate();

  const onSubmit = async (data) => {
    if (!pfp.file) {
      return setProfilePicErr("Thumbnail is required");
    }

    const response = await fetch("http://localhost/api/account/signup", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        ...data,
        pfp,
      }),
    });
    const responseData = await response.json();

    if (responseData.message) {
      toast(responseData.message, {
        type: "error",
      });
    } else {
      toast("Sign up successfull", {
        type: "success",
      });

      navigate("/");
    }
    // if (responseData.token) {
    //     localStorage.setItem('token', responseData.token);
    // }
  };

  const handleFileInput = (e) => {
    const files = e.target.files;
    if (files?.length > 0) {
      const file = files[0];
      const reader = new FileReader();
      reader.onload = (e) => {
        const extension = file.name.split(".").pop();
        const fileData = e?.target?.result;
        if (!extension || !fileData) return;
        setPfp({
          file: fileData,
          extension,
        });
        setProfilePicErr("");
      };
      reader.readAsDataURL(file);
    }
  };

  return (
    <>
      <Header />
      <div className="signUp">
        <h2>Sign Up</h2>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="form-group">
            <label>First Name</label>
            <input
              type="text"
              placeholder="Enter Your First Name"
              {...register("firstName", { required: true })}
            />
            {errors?.firstName && (
              <span className="error-mesage">{errorMessages.firstName}</span>
            )}
          </div>
          <div className="form-group">
            <label>Last Name</label>
            <input
              type="text"
              placeholder="Enter Your Last Name"
              {...register("lastName", { required: true })}
            />
            {errors?.lastName && (
              <span className="error-mesage">{errorMessages.lastName}</span>
            )}
          </div>
          <div className="form-group">
            <label>User Name</label>
            <input
              type="text"
              placeholder="Enter Your User Name"
              {...register("userName", { required: true })}
            />
            {errors?.userName && (
              <span className="error-mesage">{errorMessages.userName}</span>
            )}
          </div>
          <div className="form-group">
            <label>Email</label>
            <input
              type="email"
              placeholder="Enter Your Email"
              {...register("email", { required: true })}
            />
            {errors?.email && (
              <span className="error-mesage">{errors?.email?.message}</span>
            )}
          </div>
          <div className="form-group">
            <label>Password</label>
            <input
              type="password"
              placeholder="Enter Your Password"
              {...register("password", { required: true })}
            />
            {errors?.password && (
              <span className="error-mesage">{errors?.password?.message}</span>
            )}
          </div>
          <div className="form-group">
            <label>Country</label>
            <Controller
              name="country"
              control={control}
              placeholder="Enter Your Password"
              render={({ field }) => (
                <Select
                  {...field}
                  options={countries}
                  components={animatedComponents}
                  closeMenuOnSelect={false}
                />
              )}
            />
            {errors?.country && (
              <span className="error-mesage">{errors?.country?.message}</span>
            )}
          </div>

          <div className="form-group">
            <label>State</label>
            <Controller
              name="state"
              control={control}
              placeholder="Enter Your Password"
              render={({ field }) => (
                <Select
                  {...field}
                  options={states}
                  components={animatedComponents}
                  closeMenuOnSelect={false}
                />
              )}
            />
            {errors?.state && (
              <span className="error-mesage">{errors?.state?.message}</span>
            )}
          </div>
          <div className="form-group">
            <label>County</label>
            <Controller
              name="county"
              control={control}
              placeholder="Enter Your County"
              render={({ field }) => (
                <Select
                  {...field}
                  options={counties}
                  components={animatedComponents}
                  closeMenuOnSelect={false}
                />
              )}
            />
            {errors?.county && (
              <span className="error-mesage">{errors?.county?.message}</span>
            )}
          </div>

          <div className="form-group">
            <label>City</label>
            <Controller
              name="city"
              control={control}
              placeholder="Enter Your Password"
              render={({ field }) => (
                <Select
                  {...field}
                  options={cities}
                  components={animatedComponents}
                  closeMenuOnSelect={false}
                />
              )}
            />
            {errors?.city && (
              <span className="error-mesage">{errors?.city?.message}</span>
            )}
          </div>

          <div className="form-group">
            <label>Upload Profile Pic</label>
            <div className="files">
              <input type="file" onChange={handleFileInput} />
              <div className="ulpad_text">
                <h4>Upload Profile Pic</h4>
              </div>
              {profilePicErr && (
                <span className="error-mesage">{profilePicErr}</span>
              )}
            </div>
          </div>
          <div className="form-group">
            <button className="submin_btn" type="submit">
              Sign Up
            </button>
          </div>
        </form>
      </div>
    </>
  );
};

export default Signup;

// DOCKER_SAMPLE/web/src/components/auth/SignUp.svelte
<script lang="ts">
    import type { SignUpType } from 'src/shared/types';
    import { countries, states } from 'src/shared/constants';
    import { getContext } from 'svelte';
    import type { Writable } from 'svelte/store';
    import { fly } from 'svelte/transition';
    import ChangePfp from './PfpInput.svelte';
    let formIsFinished = false;
    let stage = getContext<Writable<number>>('stage');

    let files: FileList;
    let formData: SignUpType = {
        email: '',
        userName: '',
        password: '',
        country: '',
        city: '',
        state: '',
        firstName: '',
        lastName: '',
        pfp: {
            file: '',
            extension: '',
        },
    };
    let errorMessage = '';
    const validateForm = () => {
        let isFilled = true;
        Object.keys(formData).forEach((key) => {
            if ((formData as any)[key] === '') {
                isFilled = false;
            }
        });

        return isFilled;
    };

    const handleSubmit = async (e: SubmitEvent) => {
        e.preventDefault();
        if (!formIsFinished) return;

        const response = await fetch('/api/account/signup', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                ...formData,
            }),
        });
        const data = await response.json();
        if (data.message) {
            errorMessage = data.message;
        }
        if (data.token) {
            localStorage.setItem('token', data.token);
        }
    };

    $: formData, (formIsFinished = validateForm());
    $: if ($stage == 1 && !formIsFinished) {
        stage.set(0);
    }
</script>

<form action="POST" class="sign-up" on:submit={handleSubmit}>
    <h2>Join the Conversation</h2>
    {#if $stage == 0}
        <div class="stage">
            <div class="section">
                <h3>Basic Info</h3>
                <div class="fieldset">
                    <input
                        type="email"
                        placeholder="Email"
                        name="email"
                        required
                        bind:value={formData.email}
                    />
                    <div class="split">
                        <input
                            type="text"
                            placeholder="First Name"
                            name="firstName"
                            required
                            bind:value={formData.firstName}
                        />
                        <input
                            type="text"
                            placeholder="Last Name"
                            name="lastName"
                            required
                            bind:value={formData.lastName}
                        />
                    </div>
                    <input
                        type="text"
                        placeholder="User Name"
                        name="userName"
                        required
                        bind:value={formData.userName}
                    />
                    <input
                        type="password"
                        placeholder="Password"
                        name="password"
                        required
                        bind:value={formData.password}
                    />
                </div>
            </div>
            <div class="section">
                <h3>Location</h3>
                <div class="fieldset">
                    <select
                        name="country"
                        required
                        bind:value={formData.country}
                    >
                        <option value="">Country</option>
                        {#each countries as country}
                            <option value={country}>{country}</option>
                        {/each}
                    </select>
                    <select name="state" required bind:value={formData.state}>
                        <option value="">State</option>
                        {#each states as state}
                            <option value={state}>{state}</option>
                        {/each}
                    </select>
                    <input
                        type="text"
                        placeholder="City"
                        name="city"
                        required
                        bind:value={formData.city}
                    />
                </div>
            </div>

            <button
                disabled={!formIsFinished}
                on:click={(e) => {
                    e.preventDefault();
                    $stage = 1;
                }}>Next</button
            >
        </div>
    {/if}
    {#if $stage == 1}
        <div class="stage" in:fly={{ x: 200, duration: 400 }}>
            <h3 class="center-text">Profile Picture</h3>
            <ChangePfp bind:pfp={formData.pfp} />
            {#if errorMessage}
                <div class="error">{errorMessage}</div>
            {/if}
            <button
                disabled={!formData.pfp.file || !formData.pfp.extension}
                type="submit">Sign Up</button
            >
        </div>
    {/if}
</form>

<style lang="scss">
    .sign-up {
        overflow: hidden;
        h2 {
            text-align: center;
        }

        .stage {
            display: flex;
            flex-direction: column;
            padding: 2em 4em;
            gap: 1em;
            max-width: min(500px, 100vw);
        }
        h3 {
            transition: all 0.2s ease-in-out;
        }
        .split {
            display: flex;
            gap: 1em;
            flex-wrap: wrap;
            input {
                flex: 1;
            }
        }
    }
    .error {
        color: var(--color-warning-dark);
        font-weight: bold;
    }
    .section:focus-within {
        h3 {
            color: var(--color-primary);
        }
    }
    .fieldset {
        display: flex;
        flex-direction: column;
        gap: 0.5em;
    }
</style>
